---
- name: Deploy Hanma
  hosts: "{{ site_deploy | default('hanma_dev', true) }}"
  gather_facts: false
  become: false

  vars_files:
    - "vars/{{ site_deploy | default('hanma_dev', true) }}.yml"

  tasks:
    - name: Ensure latest Hanma Podman image is present
      containers.podman.podman_image:
        name: "{{ site_podman_image }}"
        pull: true

    - name: Ensure quadlet directory exists
      ansible.builtin.file:
        path: "{{ site_quadlet_path | dirname }}"
        state: directory
        owner: "{{ site_owner }}"
        group: "{{ site_group }}"
        mode: "u=rwx,g-rwx,o-rwx"

    - name: Deploy Hanma quadlet
      ansible.builtin.template:
        src: hanma.container.j2
        dest: "{{ site_quadlet_path }}"
        owner: "{{ site_owner }}"
        group: "{{ site_group }}"
        mode: "u=rw,g-rwx,o-rwx"
      notify:
        - Reload systemd units
        - Restart Hanma

    - name: Ensure site directory exists
      ansible.builtin.file:
        path: "{{ site_deploy_path }}"
        state: directory
        owner: "{{ site_owner }}"
        group: "{{ site_group }}"
        mode: "u=rwx,g-rwx,o-rwx"

    - name: Deploy site from Git
      ansible.builtin.git:
        repo: "{{ site_repo }}"
        dest: "{{ site_deploy_path }}"
        version: "{{ site_repo_version | default('main') }}"
        force: true

    - name: Ensure linger is enabled for user
      ansible.builtin.command: "loginctl enable-linger {{ site_owner }}"
      changed_when: false

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Start Hanma
      ansible.builtin.systemd_service:
        name: "{{ site_container_name }}.service"
        state: started
        scope: user

  handlers:
    - name: Reload systemd units
      ansible.builtin.systemd_service:
        daemon_reload: true
        scope: user

    - name: Restart Hanma
      ansible.builtin.systemd_service:
        name: "{{ site_container_name }}.service"
        state: restarted
        scope: user
