---
- name: Build and Deploy Hanma
  hosts: "{{ site_deploy | default('hanma_dev', true) }}"
  gather_facts: false
  become: false

  vars_files:
    - "vars/{{ site_deploy | default('hanma_dev', true) }}.yml"

  roles:
    - common_handlers

  tasks:
    - name: Pull Hanma image from the registry or build the image if it doesnt exist upstream
      block:
        - name: Pull the image from registy
          containers.podman.podman_image:
            name: "{{ podman_build_image_name }}"
            pull: true
            force: true
          register: hanma_image_update
          notify: Restart Hanma

      rescue:
        - name: Build local image if necessary
          block:
            - name: Image doesn't exist
              ansible.builtin.debug:
                msg: |-
                  Hanma image doesn't exist on the registry. Building image.

            - name: Build Podman container image
              ansible.builtin.include_role:
                name: podman_build

            - name: Trigger build/cleanup handlers
              ansible.builtin.meta: flush_handlers

    - name: Deploy Hanma Podman quadlet
      ansible.builtin.include_role:
        name: podman_quadlet

    - name: Enable login linger for {{ site_owner }}
      ansible.builtin.include_role:
        name: enable_linger

    - name: Deploy site
      ansible.builtin.include_role:
        name: "{{ hanma_stage_directory is defined | ternary('local_site', 'git_site') }}"

    - name: Trigger required handlers
      ansible.builtin.meta: flush_handlers

    - name: Ensure Hanma is running/restarted
      ansible.builtin.systemd_service:
        name: "{{ site_container_name }}.service"
        state: "{{ restart_site | default(false) | ternary('restarted', 'started') }}"
        scope: user
