---
- name: Create site staging area
  ansible.builtin.file:
    path: "{{ hanma_stage_directory }}_{{ site_container_name }}"
    state: directory
    mode: "u=rwx,g-rwx,o-rwx"
  delegate_to: localhost
