---
# Clone Hanma repo
# Build image
- name: Fetch Hanma source from Git
  ansible.builtin.git:
    repo: "{{ podman_build_hanma_src }}"
    dest: "{{ podman_build_build_path }}"
    version: "{{ podman_build_hanma_branch | default('main') }}"
    force: true

- name: Build Hanma container image
  containers.podman.podman_image:
    name: "{{ podman_build_image_name }}"
    pull: false
    push: false
    state: build
    build:
      cache: true
      file: "{{ podman_build_build_path }}/Containerfile"

- name: Clean up build directory
  ansible.builtin.file:
    path: "{{ podman_build_build_path }}"
    state: absent
