---
- name: Fetch Hanma source from Git
  ansible.builtin.git:
    repo: "{{ podman_build_hanma_src }}"
    dest: "{{ podman_build_build_path }}"
    version: "{{ podman_build_hanma_branch | default('main') }}"
    force: true
  notify: Build Hanma container image

- name: Clean up the old image(s) post-build
  ansible.builtin.command: "podman image prune -f --filter 'label=app=hanma'"
  changed_when: false
