---
- name: Build Hanma container image
  containers.podman.podman_image:
    name: "{{ podman_build_image_name }}"
    pull: false
    push: false
    state: build
    force: true
    build:
      cache: true
      file: "{{ podman_build_build_path }}/Containerfile"
      extra_args: "--label app={{ site_container_name }}"

- name: Clean up the old image
  ansible.builtin.command: "podman image prune -f --filter 'label=app={{ site_container_name }}'"
  changed_when: false

- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
    scope: user

- name: Restart Hanma
  ansible.builtin.set_fact:
    restart_site: true
