---
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
    scope: user

- name: Restart Hanma
  ansible.builtin.systemd_service:
    name: "{{ site_container_name }}.service"
    state: restarted
    scope: user
