---
- name: Gather system info
  ansible.builtin.import_tasks: gather_sys_info.yml

- name: Ensure deployment paths are present
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ site_owner }}"
    group: "{{ site_group }}"
    mode: "u=rwx,g-rwx,o-rwx"
  loop:
    - "{{ site_deploy_path }}"
    - "{{ site_config_path }}"
    - "{{ site_content_path }}"

- name: Deploy Hanma configuration file
  ansible.builtin.copy:
    src: files/conf/hanma.yml
    dest: "{{ site_config_path }}"
    owner: "{{ site_owner }}"
    group: "{{ site_group }}"
    mode: "u=rw,g-rwx,o-rwx"
  notify: Restart Hanma

# Permissions are set on sync; no-qa used
- name: Deploy site files to staging area
  delegate_to: localhost
  block:
    - name: Create staging area
      ansible.builtin.include_role:
        name: stage_area
        tasks_from: main.yml

    - name: Deploy index page to staging area # noqa: risky-file-permissions
      ansible.builtin.template:
        src: index.md.j2
        dest: "{{ hanma_stage_directory }}_{{ site_container_name }}/index.md"

    # Permissions are set on sync; no-qa used
    - name: Deploy static pages to staging area # noqa: risky-file-permissions
      ansible.builtin.copy:
        src: "files/site/"
        dest: "{{ hanma_stage_directory }}_{{ site_container_name }}"

- name: Push site to destination host
  ansible.builtin.include_role:
    name: synchronize_site

- name: Create staging area
  ansible.builtin.include_role:
    name: stage_area
    tasks_from: clean_stage_area.yml
